refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {m}{n}"
  rolling_file:
    kind: rolling_file
    path: log/requests.log
    encoder:
      pattern: "{d} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        pattern: log/requests_{}.log
        count: 5
        base: 1
root:
  level: info
  appenders:
    - stdout
    - rolling_file
