[package]
name = "loadfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.29"
regex = "1.5.4"
plotly = { version = "0.6.0", features = ["kaleido"] }